//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Term.DAL.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class OrderStatusesTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OrderStatusesTexts() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Term.DAL.Resources.OrderStatusesTexts", typeof(OrderStatusesTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Being сonfirmed by Supplier.
        /// </summary>
        public static string BeingConfirmedBySupplier {
            get {
                return ResourceManager.GetString("BeingConfirmedBySupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Being delivered to stock from supplier.
        /// </summary>
        public static string BeingDeliveredToStockFromSupplier {
            get {
                return ResourceManager.GetString("BeingDeliveredToStockFromSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Being prepared for shipment.
        /// </summary>
        public static string BeingPreparedForShipment {
            get {
                return ResourceManager.GetString("BeingPreparedForShipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancelled.
        /// </summary>
        public static string Cancelled {
            get {
                return ResourceManager.GetString("Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancelled by supplier.
        /// </summary>
        public static string CancelledBySupplier {
            get {
                return ResourceManager.GetString("CancelledBySupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Confirmed.
        /// </summary>
        public static string Confirmed {
            get {
                return ResourceManager.GetString("Confirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delivered.
        /// </summary>
        public static string Delivered {
            get {
                return ResourceManager.GetString("Delivered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delivered.
        /// </summary>
        public static string DeliveredToClient {
            get {
                return ResourceManager.GetString("DeliveredToClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delivered to the branch.
        /// </summary>
        public static string DeliveredToTheBranch {
            get {
                return ResourceManager.GetString("DeliveredToTheBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delivering.
        /// </summary>
        public static string Delivering {
            get {
                return ResourceManager.GetString("Delivering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Loading.
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Lost.
        /// </summary>
        public static string Lost {
            get {
                return ResourceManager.GetString("Lost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на NewOrderByClient.
        /// </summary>
        public static string NewOrderByClient {
            get {
                return ResourceManager.GetString("NewOrderByClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на NewOrderByDpd.
        /// </summary>
        public static string NewOrderByDpd {
            get {
                return ResourceManager.GetString("NewOrderByDpd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на OnRoad.
        /// </summary>
        public static string OnRoad {
            get {
                return ResourceManager.GetString("OnRoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на OnTerminal.
        /// </summary>
        public static string OnTerminal {
            get {
                return ResourceManager.GetString("OnTerminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на OnTerminalDelivery.
        /// </summary>
        public static string OnTerminalDelivery {
            get {
                return ResourceManager.GetString("OnTerminalDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на OnTerminalPickup.
        /// </summary>
        public static string OnTerminalPickup {
            get {
                return ResourceManager.GetString("OnTerminalPickup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на On the way.
        /// </summary>
        public static string OnTheWay {
            get {
                return ResourceManager.GetString("OnTheWay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Partially loaded.
        /// </summary>
        public static string PartiallyLoaded {
            get {
                return ResourceManager.GetString("PartiallyLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Partially sold.
        /// </summary>
        public static string PartiallySold {
            get {
                return ResourceManager.GetString("PartiallySold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Problem.
        /// </summary>
        public static string Problem {
            get {
                return ResourceManager.GetString("Problem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ReturnedFromDelivery.
        /// </summary>
        public static string ReturnedFromDelivery {
            get {
                return ResourceManager.GetString("ReturnedFromDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Shipped completely.
        /// </summary>
        public static string ShippedCompletely {
            get {
                return ResourceManager.GetString("ShippedCompletely", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Shipped.
        /// </summary>
        public static string ShippedForSale {
            get {
                return ResourceManager.GetString("ShippedForSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Shipped partially.
        /// </summary>
        public static string ShippedPartially {
            get {
                return ResourceManager.GetString("ShippedPartially", resourceCulture);
            }
        }
    }
}
