// <auto-generated />
namespace YstProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class PriceIsPrepay2_AddedTocart : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PriceIsPrepay2_AddedTocart));
        
        string IMigrationMetadata.Id
        {
            get { return "201709281315498_PriceIsPrepay2_AddedTocart"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
