//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18444
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Этот исходный текст был создан автоматически: Microsoft.VSDesigner, версия: 4.0.30319.18444.
// 
#pragma warning disable 1591

namespace YstProject.WebReferenceTerm {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using YstStore.Domain.Soapmodels;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceTerminalSoapBinding", Namespace="http://37.1.84.50:8080/ServiceTerminal")]
    public partial class ServiceTerminal : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CreateOrderOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteOrderOperationCompleted;
        
        //added manually
        private System.Threading.SendOrPostCallback ChangeOrderOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ServiceTerminal() {
            this.Url = global::YstProject.Properties.Settings.Default.YstProject_WebReferenceTerm_ServiceTerminal;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CreateOrderCompletedEventHandler CreateOrderCompleted;
        
        /// <remarks/>
        public event DeleteOrderCompletedEventHandler DeleteOrderCompleted;

        /// <remarks/>
        public event ChangeOrderCompletedEventHandler ChangeOrderCompleted;

/*
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://37.1.84.50:8080/ServiceTerminal#ServiceTerminal:DeleteRestoreSeasonOrder", RequestNamespace = "http://37.1.84.50:8080/ServiceTerminal", ResponseNamespace = "http://37.1.84.50:8080/ServiceTerminal", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public ResultDel DeleteRestoreSeasonOrder(string SeasonOrderGUID, bool Delete)
        {
            object[] results = this.Invoke("DeleteRestoreSeasonOrder", new object[] {
                        SeasonOrderGUID,
                        Delete});
            return ((ResultDel)(results[0]));
        }
        /// <remarks/>

        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://37.1.84.50:8080/ServiceTerminal#ServiceTerminal:CreateSeasonOrder", RequestNamespace = "http://37.1.84.50:8080/ServiceTerminal", ResponseNamespace = "http://37.1.84.50:8080/ServiceTerminal", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public ResultSeasonOrder CreateSeasonOrder(string Partner, 
            [System.Xml.Serialization.XmlArrayItemAttribute("Products", Namespace = "http://37.1.84.50:8080/Terminal", IsNullable = false)] SoapProduct[] Goods, 
            string Storage, 
            [System.Xml.Serialization.XmlElementAttribute(DataType = "date")] System.DateTime ActionDate, 
            [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string Comment, 
             string SeasonOrderGUID)
        {
            object[] results = this.Invoke("CreateSeasonOrder", new object[] {
                        Partner,
                        Goods,
                        Storage,
                        ActionDate,
                        Comment,
                        SeasonOrderGUID});
            return ((ResultSeasonOrder)(results[0]));
        }

    */
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://37.1.84.50:8080/ServiceTerminal#ServiceTerminal:CreateOrder", RequestNamespace="http://37.1.84.50:8080/ServiceTerminal", ResponseNamespace="http://37.1.84.50:8080/ServiceTerminal", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public Result CreateOrder(string Partner, int PointId, [System.Xml.Serialization.XmlArrayItemAttribute("Products", Namespace = "http://37.1.84.50:8080/Terminal", IsNullable = false)] SoapProduct[] Goods, string Comment, string ShippingDay, bool isReserve, bool TransportCompany)
        {
            object[] results = this.Invoke("CreateOrder", new object[] {
                        Partner,
                        PointId,
                        Goods,
                        Comment,
            ShippingDay,isReserve,TransportCompany});
            return ((Result)(results[0]));
        }
        
        /// <remarks/>
        public void CreateOrderAsync(string Partner, int PointId, SoapProduct[] Goods, string Comment, string ShippingDay, bool isReserve)
        {
            this.CreateOrderAsync(Partner, PointId, Goods, Comment, ShippingDay, isReserve,null);
        }
        
        /// <remarks/>
        public void CreateOrderAsync(string Partner, int PointId, SoapProduct[] Goods, string Comment, string ShippingDay, bool isReserve, object userState) {
            if ((this.CreateOrderOperationCompleted == null)) {
                this.CreateOrderOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateOrderOperationCompleted);
            }
            this.InvokeAsync("CreateOrder", new object[] {
                        Partner,
                        PointId,
                        Goods,
                        Comment,ShippingDay,  isReserve}, this.CreateOrderOperationCompleted, userState);
        }
        
        private void OnCreateOrderOperationCompleted(object arg) {
            if ((this.CreateOrderCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateOrderCompleted(this, new CreateOrderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://37.1.84.50:8080/ServiceTerminal#ServiceTerminal:DeleteOrder", RequestNamespace="http://37.1.84.50:8080/ServiceTerminal", ResponseNamespace="http://37.1.84.50:8080/ServiceTerminal", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public ResultDel DeleteOrder(string OrderGUID) {
            object[] results = this.Invoke("DeleteOrder", new object[] {
                        OrderGUID});
            return ((ResultDel)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteOrderAsync(string OrderGUID) {
            this.DeleteOrderAsync(OrderGUID, null);
        }
        
        /// <remarks/>
        public void DeleteOrderAsync(string OrderGUID, object userState) {
            if ((this.DeleteOrderOperationCompleted == null)) {
                this.DeleteOrderOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteOrderOperationCompleted);
            }
            this.InvokeAsync("DeleteOrder", new object[] {
                        OrderGUID}, this.DeleteOrderOperationCompleted, userState);
        }
        
        private void OnDeleteOrderOperationCompleted(object arg) {
            if ((this.DeleteOrderCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteOrderCompleted(this, new DeleteOrderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }


         //-- begin added manually
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://37.1.84.50:8080/ServiceTerminal#ServiceTerminal:ChangeOrder", RequestNamespace = "http://37.1.84.50:8080/ServiceTerminal", ResponseNamespace = "http://37.1.84.50:8080/ServiceTerminal", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public ResultDel ChangeOrder(string OrderGUID, [System.Xml.Serialization.XmlArrayItemAttribute("Products", Namespace = "http://37.1.84.50:8080/Terminal", IsNullable = false)] SoapProduct[] Goods, string Comment, bool isReserve, string ShippingDay)
        {
            object[] results = this.Invoke("ChangeOrder", new object[] {
                        OrderGUID,
                        Goods,
                        Comment,isReserve,ShippingDay});
            return ((ResultDel)(results[0]));
        }

        /// <remarks/>
        public void ChangeOrderAsync(string OrderGUID, SoapProduct[] Goods)
        {
            this.ChangeOrderAsync(OrderGUID, Goods, null);
        }

        /// <remarks/>
        public void ChangeOrderAsync(string OrderGUID, SoapProduct[] Goods, object userState)
        {
            if ((this.ChangeOrderOperationCompleted == null))
            {
                this.ChangeOrderOperationCompleted = new System.Threading.SendOrPostCallback(this.OnChangeOrderOperationCompleted);
            }
            this.InvokeAsync("ChangeOrder", new object[] {
                        OrderGUID,
                        Goods}, this.ChangeOrderOperationCompleted, userState);
        }

        private void OnChangeOrderOperationCompleted(object arg)
        {
            if ((this.ChangeOrderCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ChangeOrderCompleted(this, new ChangeOrderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        //-- end added manually

        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    /*
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://37.1.84.50:8080/Terminal")]
    public partial class SoapProduct {
        
        private string codeField;
        
        private int quantityField;
        
        private string storageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Code")]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Quantity")]
        public int Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Storage")]
        public string Storage {
            get {
                return this.storageField;
            }
            set {
                this.storageField = value;
            }
        }
    }



    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://37.1.84.50:8080/Terminal")]
    public partial class SoapProductSeasonOrder
    {

        private int rowNumberField;

        private string codeField;

        private int quantityField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RowNumber")]
        public int RowNumber
        {
            get
            {
                return this.rowNumberField;
            }
            set
            {
                this.rowNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Code")]
        public string Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Quantity")]
        public int Quantity
        {
            get
            {
                return this.quantityField;
            }
            set
            {
                this.quantityField = value;
            }
        }
    }
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://37.1.84.50:8080/Terminal")]
    public partial class ResultDel {
        
        private bool successField;
        
        private string errorField;
        
        /// <remarks/>
        public bool Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        public string Error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://37.1.84.50:8080/Terminal")]
    public partial class ProductResult {
        
        private string codeField;
        
        private int quantityField;
        
        private string storageField;
        
        private string orderGUIDField;

        private string orderNumberIn1S;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Code")]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Quantity")]
        public int Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Storage")]
        public string Storage {
            get {
                return this.storageField;
            }
            set {
                this.storageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OrderGUID", IsNullable=true)]
        public string OrderGUID {
            get {
                return this.orderGUIDField;
            }
            set {
                this.orderGUIDField = value;
            }
        }
        [System.Xml.Serialization.XmlElementAttribute("OrderNumber", IsNullable = true)]
        public string OrderNumberIn1S
        {
            get
            {
                return this.orderNumberIn1S;
            }
            set
            {
                this.orderNumberIn1S = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://37.1.84.50:8080/Terminal")]
    public partial class Result {
        
        private ProductResult[] productsField;
        
        private bool successField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("ProductsResult", IsNullable=false)]
        public ProductResult[] Products {
            get {
                return this.productsField;
            }
            set {
                this.productsField = value;
            }
        }
        
        /// <remarks/>
        public bool Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
    }


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://37.1.84.50:8080/Terminal")]
    public partial class ResultSeasonOrder
    {
        private ProductResult[] productsField;

        private bool successField;

  //      private string orderNumberField;

    //    private string orderGUIDField;

        private string errorField;

        /// <remarks/>
        public bool Success
        {
            get
            {
                return this.successField;
            }
            set
            {
                this.successField = value;
            }
        }

        /// <remarks/>
        public string Error
        {
            get
            {
                return this.errorField;
            }
            set
            {
                this.errorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("ProductsResult", IsNullable = false)]
        public ProductResult[] Products
        {
            get
            {
                return this.productsField;
            }
            set
            {
                this.productsField = value;
            }
        }
    }
*/

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void CreateOrderCompletedEventHandler(object sender, CreateOrderCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateOrderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateOrderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Result Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Result)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void DeleteOrderCompletedEventHandler(object sender, DeleteOrderCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteOrderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteOrderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResultDel Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResultDel)(this.results[0]));
            }
        }
    }


    // added  manually
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void ChangeOrderCompletedEventHandler(object sender, ChangeOrderCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ChangeOrderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal ChangeOrderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public ResultDel Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((ResultDel)(this.results[0]));
            }
        }
    }

}

#pragma warning restore 1591