//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Term.Web.Views.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Agreement {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Agreement() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Term.Web.Views.Resources.Agreement", typeof(Agreement).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на User agreement.
        /// </summary>
        public static string Agreement1 {
            get {
                return ResourceManager.GetString("Agreement1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1.7. The Present Agreement is a public offer. At the time the User is issued the access to the materials of online-service «TERMINAL YST», he is considered to accept the conditions of the Agreement..
        /// </summary>
        public static string Agreement10 {
            get {
                return ResourceManager.GetString("Agreement10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1.8. All possible disputes raised from the Agreement or connected with it are subject to consideration, including dispute related to any change, performance, violation, termination, declaring agreement void or unconcluded,  and to be sent for settlement to the Arbitrary court of independent non-for-profit organization «Center of Arbitrary court proceedings and mediation» (№ 1147600000866, administration office: 150014, Yaroslavskaya oblast, Saltykova Shedrina street, h. 21, office 420) in accordance with th [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string Agreement11 {
            get {
                return ResourceManager.GetString("Agreement11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1.9. Nothing in the Agreement can be interpreted as establishment of any agency relations, companionship, cooperation, employment, or any other relations between the User and JSC TC “Yarshintorg”, not stipulated directly in the Agreement..
        /// </summary>
        public static string Agreement12 {
            get {
                return ResourceManager.GetString("Agreement12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1.10. In case the Court declares any provision of the Agreement as void or not subject to obligatory implementation, the other provisions of the Agreement stay in effect..
        /// </summary>
        public static string Agreement13 {
            get {
                return ResourceManager.GetString("Agreement13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1.11. If JSC TC “Yarshintorg” fails to act immediately in case any User violates the Agreement provisions, JSC TC “Yarshintorg”  still has the right to take later corresponding measures to protect its interests and rights in accordance with legislation..
        /// </summary>
        public static string Agreement14 {
            get {
                return ResourceManager.GetString("Agreement14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1.12. The User is allowed to use online service «TERMINAL YST» only after he passes registration and authorization in accordance with the established procedure..
        /// </summary>
        public static string Agreement15 {
            get {
                return ResourceManager.GetString("Agreement15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1.13. Technical, organizational and commercial conditions for the usage of online service «TERMINAL YST», as well as its functional possibilities are stipulated in the present Agreement, and also individual publishing on the Webpage..
        /// </summary>
        public static string Agreement16 {
            get {
                return ResourceManager.GetString("Agreement16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 2. Information on the product.
        /// </summary>
        public static string Agreement17 {
            get {
                return ResourceManager.GetString("Agreement17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 2.1. Each photo-sample is followed by text information: price and description of the product. The quality of adjustment and screen parameters of the User’s computer can distort the color of the product. The User has the right to use feedback form to clarify the characteristics of the required product..
        /// </summary>
        public static string Agreement18 {
            get {
                return ResourceManager.GetString("Agreement18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 2.2. The price, indicated in online service «TERMINAL YST» can be changed by JSC TC “Yarshintorg” unilaterally. The price for the paid goods is not subject to any changes..
        /// </summary>
        public static string Agreement19 {
            get {
                return ResourceManager.GetString("Agreement19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на for online service «TERMINAL YST».
        /// </summary>
        public static string Agreement2 {
            get {
                return ResourceManager.GetString("Agreement2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 3. Rights, responsibilities and obligations of the User..
        /// </summary>
        public static string Agreement20 {
            get {
                return ResourceManager.GetString("Agreement20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 3.1. The User is obliged to recognize legal effect of the information on the online service «TERMINAL YST» within the whole term of Agreement, including product price, product range, terms of delivery, etc., and recognize the legal effect of all the actions taken from his/her name under hers/his unique login and password on the online service «TERMINAL YST»..
        /// </summary>
        public static string Agreement21 {
            get {
                return ResourceManager.GetString("Agreement21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 3.2. The User is forbidden to transfer to the 3d parties any data published on «TERMINAL YST» including, but not restricted to: product range, pricing, delivery terms, other information..
        /// </summary>
        public static string Agreement22 {
            get {
                return ResourceManager.GetString("Agreement22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 3.3. The User agrees not to take any actions, that can be considered as violation of the Russian law or international rights norms, including violation of intellectual property rights, author’s rights and related rights, as well as any other actions that lead or can lead to malfunctioning of the Website and online service..
        /// </summary>
        public static string Agreement23 {
            get {
                return ResourceManager.GetString("Agreement23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 3.4. The chosen Login and Password are required and sufficient information for  service sign-in. The User has no right to transfer his Login and Password to 3d parties, he takes full responsibility for these data safety and the way of their protection..
        /// </summary>
        public static string Agreement24 {
            get {
                return ResourceManager.GetString("Agreement24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 3.5. The User can create orders, reserve the goods on online service «TERMINAL YST», receive the order confirmation, and edit the order, follow-up the status and flow..
        /// </summary>
        public static string Agreement25 {
            get {
                return ResourceManager.GetString("Agreement25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The User can individually set the sale price:.
        /// </summary>
        public static string Agreement26 {
            get {
                return ResourceManager.GetString("Agreement26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на In relation to basic price.
        /// </summary>
        public static string Agreement27 {
            get {
                return ResourceManager.GetString("Agreement27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на In relation to purchase price.
        /// </summary>
        public static string Agreement28 {
            get {
                return ResourceManager.GetString("Agreement28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на In relation to recommended price.
        /// </summary>
        public static string Agreement29 {
            get {
                return ResourceManager.GetString("Agreement29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1. General provision..
        /// </summary>
        public static string Agreement3 {
            get {
                return ResourceManager.GetString("Agreement3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 3.6. The User can determine the delivery address; leave the comments to the order..
        /// </summary>
        public static string Agreement30 {
            get {
                return ResourceManager.GetString("Agreement30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 3.7. The user can not use information of online service «TERMINAL YST» without permission of JSC TC “Yarshintorg”..
        /// </summary>
        public static string Agreement31 {
            get {
                return ResourceManager.GetString("Agreement31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 3.8. Comments or any other notes left by the User on online service «TERMINAL YST» shouldn’t contradict to the RF legislation and general norms of ethics..
        /// </summary>
        public static string Agreement32 {
            get {
                return ResourceManager.GetString("Agreement32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 3.9. The User is aware that JSC TC “Yarshintorg” doesn’t take any responsibility for visiting or usage of any links to external recourses that can be found in the content of «TERMINAL YST»..
        /// </summary>
        public static string Agreement33 {
            get {
                return ResourceManager.GetString("Agreement33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 3.10. The User accepts the clause that all the materials of online service «TERMINAL YST» or any part of them can be accompanied with the advertisement. The User agrees JSC TC “Yarshintorg” doesn’t take any responsibility nor has no obligations connected with this advertisement..
        /// </summary>
        public static string Agreement34 {
            get {
                return ResourceManager.GetString("Agreement34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 3.11. The User confirms that he is acknowledged with all Clauses of the present Agreement and accepts them unconditionally..
        /// </summary>
        public static string Agreement35 {
            get {
                return ResourceManager.GetString("Agreement35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 4. Rights, obligations and liabilities of JSC TC “Yarshintorg”.
        /// </summary>
        public static string Agreement36 {
            get {
                return ResourceManager.GetString("Agreement36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 4.1. In case the User violates the present Agreement, as well as the corresponding Delivery Agreement, JSC TC “Yarshintorg” has right to temporarily stop or completely deny the access of the User to online service «TERMINAL YST»..
        /// </summary>
        public static string Agreement37 {
            get {
                return ResourceManager.GetString("Agreement37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 4.2. JSC TC “Yarshintorg” doesn’t take responsibility for the following parameters of car batteries, established by the producer: crank current, external design..
        /// </summary>
        public static string Agreement38 {
            get {
                return ResourceManager.GetString("Agreement38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 4.3. JSC TC “Yarshintorg” doesn’t take responsibility for incorrectly selected goods, as the information on the product search is referential..
        /// </summary>
        public static string Agreement39 {
            get {
                return ResourceManager.GetString("Agreement39", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1.1. The present agreement is concluded between the User and JSC TC “Yarshintorg” for the usage of online system «TERMINAL YST»..
        /// </summary>
        public static string Agreement4 {
            get {
                return ResourceManager.GetString("Agreement4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 4.4. All the conditions/requirements to the order, indicated by the User (chosen products, date and delivery address) JSC TC “Yarshintorg” accepts as required action to be taken. In case of incorrect order data, the responsibility stays with the User..
        /// </summary>
        public static string Agreement40 {
            get {
                return ResourceManager.GetString("Agreement40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 4.5. JSC TC “Yarshintorg” doesn’t take responsibility for the pricing established by the User for further sale on online service «TERMINAL YST»..
        /// </summary>
        public static string Agreement41 {
            get {
                return ResourceManager.GetString("Agreement41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 4.6. In case the goods are not available the stock, JSC TC “Yarshintorg” is obliged to notify the User (via phone or e-mail)..
        /// </summary>
        public static string Agreement42 {
            get {
                return ResourceManager.GetString("Agreement42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 4.7. Orders received before 13-00 from the Users of online service «TERMINAL YST» in the following regions: Moscow, Moscow region, Saint-Petersburg, Leningradskiy region, Ivanovo and Ivanovsky region, Vladimir and Vladimirskiy region, Kostroma and Kostromskaya region, Vologda, will be prepared for shipment on the same day. Orders from the same regions received after 13-00 will be shipped on the following day after orders time closure..
        /// </summary>
        public static string Agreement43 {
            get {
                return ResourceManager.GetString("Agreement43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 4.8. Orders received from the Users of online service «TERMINAL YST» from Rostovskiy region, Stavropol and Krasnodar regions, JSC TC “Yarshintorg”  is obliged to ship 3 times a week.  Orders from Users of online service «TERMINAL YST» in Yekaterinburg, are to be shipped once a week. The delivery to other regions is to be agreed separately..
        /// </summary>
        public static string Agreement44 {
            get {
                return ResourceManager.GetString("Agreement44", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 4.9. JSC TC “Yarshintorg” doesn’t take responsibility for any damage to the User, caused as a result of improper usage of the goods, ordered via online service «TERMINAL YST»..
        /// </summary>
        public static string Agreement45 {
            get {
                return ResourceManager.GetString("Agreement45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 4.10. JSC TC “Yarshintorg” doesn’t take any responsibility or indirect obligations for any potential or occured losses and damages, related to any content of online service «TERMINAL YST», registration of author’s right or information about this registration; good and services available or received via external websites, resources, or any other user’s relation that he started using  the information of the Webpage or links to external resources..
        /// </summary>
        public static string Agreement46 {
            get {
                return ResourceManager.GetString("Agreement46", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на I accept the agreement..
        /// </summary>
        public static string Agreement47 {
            get {
                return ResourceManager.GetString("Agreement47", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1.2. Online service «TERMINAL YST» is the ownership of  JSC TC “Yarshintorg” and it is located at the address: http://terminal.yst.ru (hereinafter – Website of online service «TERMINAL YST»)..
        /// </summary>
        public static string Agreement5 {
            get {
                return ResourceManager.GetString("Agreement5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1.3. The User is to be any legal person, private person, self-employed entrepreneur, able to receive and pay for the ordered goods in the order and on the conditions, stipulated in the Present Agreement and established by the RF legislation..
        /// </summary>
        public static string Agreement6 {
            get {
                return ResourceManager.GetString("Agreement6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1.4. JSC TC “Yarshintorg” has the right to change the conditions of the Present Agreement unilaterally. These changes come into force at the moment the new Agreement is published on the web page. In case the User doesn’t agree with the introduced changes he has to reject the access and terminate using the «TERMINAL YST»..
        /// </summary>
        public static string Agreement7 {
            get {
                return ResourceManager.GetString("Agreement7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1.5. The Present Agreement should be regarded in the form and wording as it is published on online service «TERMINAL YST», and should be used and interpreted in accordance with RF legislation..
        /// </summary>
        public static string Agreement8 {
            get {
                return ResourceManager.GetString("Agreement8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1.6. The use of materials and services of online service «TERMINAL YST» is subject to the norms of the active legislation of the Russian Federation..
        /// </summary>
        public static string Agreement9 {
            get {
                return ResourceManager.GetString("Agreement9", resourceCulture);
            }
        }
    }
}
