//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Term.Web.Views.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ForSearchResult {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ForSearchResult() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Term.Web.Views.Resources.ForSearchResult", typeof(ForSearchResult).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Action.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Added.
        /// </summary>
        public static string Added {
            get {
                return ResourceManager.GetString("Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на All.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Alloy and steel wheels.
        /// </summary>
        public static string AlloyAndSteel {
            get {
                return ResourceManager.GetString("AlloyAndSteel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на All Replica.
        /// </summary>
        public static string AllReplica {
            get {
                return ResourceManager.GetString("AllReplica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Allseason.
        /// </summary>
        public static string Allseason {
            get {
                return ResourceManager.GetString("Allseason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на All.
        /// </summary>
        public static string AllShip {
            get {
                return ResourceManager.GetString("AllShip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Amount.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Analogs.
        /// </summary>
        public static string Analogs {
            get {
                return ResourceManager.GetString("Analogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Article.
        /// </summary>
        public static string Article {
            get {
                return ResourceManager.GetString("Article", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Available.
        /// </summary>
        public static string Available {
            get {
                return ResourceManager.GetString("Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Barcode.
        /// </summary>
        public static string Barcode {
            get {
                return ResourceManager.GetString("Barcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Brand.
        /// </summary>
        public static string Brand {
            get {
                return ResourceManager.GetString("Brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на By brand.
        /// </summary>
        public static string ByBrand {
            get {
                return ResourceManager.GetString("ByBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на by car.
        /// </summary>
        public static string ByCar {
            get {
                return ResourceManager.GetString("ByCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на by parameters.
        /// </summary>
        public static string ByParam {
            get {
                return ResourceManager.GetString("ByParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на By price.
        /// </summary>
        public static string ByPrice {
            get {
                return ResourceManager.GetString("ByPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Capacity.
        /// </summary>
        public static string Capacity {
            get {
                return ResourceManager.GetString("Capacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Car parameters.
        /// </summary>
        public static string CarParam {
            get {
                return ResourceManager.GetString("CarParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Category name.
        /// </summary>
        public static string CategoryName {
            get {
                return ResourceManager.GetString("CategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select batteries by car.
        /// </summary>
        public static string ChooseAkbByCar {
            get {
                return ResourceManager.GetString("ChooseAkbByCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Choose battery.
        /// </summary>
        public static string ChooseBattery {
            get {
                return ResourceManager.GetString("ChooseBattery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Choose truck tyres.
        /// </summary>
        public static string ChooseCargoTyres {
            get {
                return ResourceManager.GetString("ChooseCargoTyres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Choose wheels.
        /// </summary>
        public static string ChooseDisks {
            get {
                return ResourceManager.GetString("ChooseDisks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Choose orders.
        /// </summary>
        public static string ChooseOrders {
            get {
                return ResourceManager.GetString("ChooseOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Choose sales.
        /// </summary>
        public static string ChooseSales {
            get {
                return ResourceManager.GetString("ChooseSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Choose orders.
        /// </summary>
        public static string ChooseSeasonOrders {
            get {
                return ResourceManager.GetString("ChooseSeasonOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на To choose brand.
        /// </summary>
        public static string ChooseSupplier {
            get {
                return ResourceManager.GetString("ChooseSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Choose tyres .
        /// </summary>
        public static string ChooseTyres {
            get {
                return ResourceManager.GetString("ChooseTyres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Clear.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на clear all.
        /// </summary>
        public static string ClearAll {
            get {
                return ResourceManager.GetString("ClearAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Search by Code/article.
        /// </summary>
        public static string CodeOrArt {
            get {
                return ResourceManager.GetString("CodeOrArt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Color.
        /// </summary>
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Comment.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Crank current.
        /// </summary>
        public static string CrankCurrent {
            get {
                return ResourceManager.GetString("CrankCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на days.
        /// </summary>
        public static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Days other stock.
        /// </summary>
        public static string DaysOtherStock {
            get {
                return ResourceManager.GetString("DaysOtherStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delivery time.
        /// </summary>
        public static string DeliveryTime {
            get {
                return ResourceManager.GetString("DeliveryTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Diameter.
        /// </summary>
        public static string Diameter {
            get {
                return ResourceManager.GetString("Diameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Dimensions.
        /// </summary>
        public static string Dimensions {
            get {
                return ResourceManager.GetString("Dimensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Entry price.
        /// </summary>
        public static string EntryPrice {
            get {
                return ResourceManager.GetString("EntryPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ET to.
        /// </summary>
        public static string ETto {
            get {
                return ResourceManager.GetString("ETto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Factory.
        /// </summary>
        public static string Factory {
            get {
                return ResourceManager.GetString("Factory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Forged.
        /// </summary>
        public static string Forged {
            get {
                return ResourceManager.GetString("Forged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на friction.
        /// </summary>
        public static string Friction {
            get {
                return ResourceManager.GetString("Friction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на From on way.
        /// </summary>
        public static string FromOnWay {
            get {
                return ResourceManager.GetString("FromOnWay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на From stock.
        /// </summary>
        public static string FromStock {
            get {
                return ResourceManager.GetString("FromStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Group.
        /// </summary>
        public static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Height.
        /// </summary>
        public static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Holes.
        /// </summary>
        public static string Holes {
            get {
                return ResourceManager.GetString("Holes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Set (more than 4 items).
        /// </summary>
        public static string IsSet4Items {
            get {
                return ResourceManager.GetString("IsSet4Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Items:.
        /// </summary>
        public static string Items {
            get {
                return ResourceManager.GetString("Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на List.
        /// </summary>
        public static string List {
            get {
                return ResourceManager.GetString("List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Load Index.
        /// </summary>
        public static string LoadIndex {
            get {
                return ResourceManager.GetString("LoadIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Manufacturer&apos;s code.
        /// </summary>
        public static string ManufacturerCode {
            get {
                return ResourceManager.GetString("ManufacturerCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Manufacturer сountry.
        /// </summary>
        public static string ManufacturerCountry {
            get {
                return ResourceManager.GetString("ManufacturerCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Model.
        /// </summary>
        public static string Model {
            get {
                return ResourceManager.GetString("Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на $.
        /// </summary>
        public static string MoneyEn {
            get {
                return ResourceManager.GetString("MoneyEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string MoneyRu {
            get {
                return ResourceManager.GetString("MoneyRu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Item:.
        /// </summary>
        public static string MsgAddToCart1 {
            get {
                return ResourceManager.GetString("MsgAddToCart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на added to cart..
        /// </summary>
        public static string MsgAddToCart2 {
            get {
                return ResourceManager.GetString("MsgAddToCart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Amount:.
        /// </summary>
        public static string MsgAddToCart3 {
            get {
                return ResourceManager.GetString("MsgAddToCart3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на was removed..
        /// </summary>
        public static string MsgDelFromCart1 {
            get {
                return ResourceManager.GetString("MsgDelFromCart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Item not found..
        /// </summary>
        public static string MsgDelFromCart2 {
            get {
                return ResourceManager.GetString("MsgDelFromCart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No studs.
        /// </summary>
        public static string NoShip {
            get {
                return ResourceManager.GetString("NoShip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Parameters.
        /// </summary>
        public static string Param {
            get {
                return ResourceManager.GetString("Param", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Type.
        /// </summary>
        public static string ParentName {
            get {
                return ResourceManager.GetString("ParentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Passenger car tyres.
        /// </summary>
        public static string PassengerTyres {
            get {
                return ResourceManager.GetString("PassengerTyres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Perfect for.
        /// </summary>
        public static string Perfect_for {
            get {
                return ResourceManager.GetString("Perfect_for", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Permitted tire sizes.
        /// </summary>
        public static string Permitted_tire_sizes {
            get {
                return ResourceManager.GetString("Permitted_tire_sizes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на On page.
        /// </summary>
        public static string PerPage {
            get {
                return ResourceManager.GetString("PerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Photo.
        /// </summary>
        public static string Photo {
            get {
                return ResourceManager.GetString("Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Polarity.
        /// </summary>
        public static string Polarity {
            get {
                return ResourceManager.GetString("Polarity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Price.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на PriceRecIm.
        /// </summary>
        public static string PriceRecIm {
            get {
                return ResourceManager.GetString("PriceRecIm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на PriceRecRozn.
        /// </summary>
        public static string PriceRecRozn {
            get {
                return ResourceManager.GetString("PriceRecRozn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Supplier.
        /// </summary>
        public static string ProducerName {
            get {
                return ResourceManager.GetString("ProducerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Product name.
        /// </summary>
        public static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на (Rear).
        /// </summary>
        public static string Rear {
            get {
                return ResourceManager.GetString("Rear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Replica by car.
        /// </summary>
        public static string ReplicaByAuto {
            get {
                return ResourceManager.GetString("ReplicaByAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rest Ekb.
        /// </summary>
        public static string RestEkb {
            get {
                return ResourceManager.GetString("RestEkb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rest Msk.
        /// </summary>
        public static string RestMsk {
            get {
                return ResourceManager.GetString("RestMsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rest other stock.
        /// </summary>
        public static string RestOtherStock {
            get {
                return ResourceManager.GetString("RestOtherStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rest Rostov.
        /// </summary>
        public static string RestRnd {
            get {
                return ResourceManager.GetString("RestRnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rest Spb.
        /// </summary>
        public static string RestSpb {
            get {
                return ResourceManager.GetString("RestSpb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rest Yaroslavl.
        /// </summary>
        public static string RestYar {
            get {
                return ResourceManager.GetString("RestYar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Retail price.
        /// </summary>
        public static string RetailPrice {
            get {
                return ResourceManager.GetString("RetailPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Retail price.
        /// </summary>
        public static string RetailPrice2 {
            get {
                return ResourceManager.GetString("RetailPrice2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sale.
        /// </summary>
        public static string Sale {
            get {
                return ResourceManager.GetString("Sale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Search by car batteries parameters.
        /// </summary>
        public static string SearchByCarBatarisSize {
            get {
                return ResourceManager.GetString("SearchByCarBatarisSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Search by tyre size.
        /// </summary>
        public static string SearchByTyreSize {
            get {
                return ResourceManager.GetString("SearchByTyreSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Search by wheel parameters.
        /// </summary>
        public static string SearchByWheelSize {
            get {
                return ResourceManager.GetString("SearchByWheelSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Search result.
        /// </summary>
        public static string SearchResult {
            get {
                return ResourceManager.GetString("SearchResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Season.
        /// </summary>
        public static string Season {
            get {
                return ResourceManager.GetString("Season", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Studs.
        /// </summary>
        public static string Ship {
            get {
                return ResourceManager.GetString("Ship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на no studs.
        /// </summary>
        public static string ShipNoShip {
            get {
                return ResourceManager.GetString("ShipNoShip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Size 1.
        /// </summary>
        public static string SizeOther_1 {
            get {
                return ResourceManager.GetString("SizeOther_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Size 2.
        /// </summary>
        public static string SizeOther_2 {
            get {
                return ResourceManager.GetString("SizeOther_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sort.
        /// </summary>
        public static string Sort {
            get {
                return ResourceManager.GetString("Sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sort by.
        /// </summary>
        public static string SortBy {
            get {
                return ResourceManager.GetString("SortBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Speed Index.
        /// </summary>
        public static string SpeedIndex {
            get {
                return ResourceManager.GetString("SpeedIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Stock number.
        /// </summary>
        public static string StockNumber {
            get {
                return ResourceManager.GetString("StockNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Summer.
        /// </summary>
        public static string Summer {
            get {
                return ResourceManager.GetString("Summer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tile.
        /// </summary>
        public static string Tile {
            get {
                return ResourceManager.GetString("Tile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add to cart.
        /// </summary>
        public static string ToCart {
            get {
                return ResourceManager.GetString("ToCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на To search.
        /// </summary>
        public static string ToSearch {
            get {
                return ResourceManager.GetString("ToSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Truck tyres.
        /// </summary>
        public static string TruckTyres {
            get {
                return ResourceManager.GetString("TruckTyres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на CAR.
        /// </summary>
        public static string VehicleCar {
            get {
                return ResourceManager.GetString("VehicleCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Vehicle fitment guide.
        /// </summary>
        public static string VehicleFitmentGuide {
            get {
                return ResourceManager.GetString("VehicleFitmentGuide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MODEL AND MODIFICATIONS.
        /// </summary>
        public static string VehicleModel {
            get {
                return ResourceManager.GetString("VehicleModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Volume.
        /// </summary>
        public static string Volume {
            get {
                return ResourceManager.GetString("Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Weight.
        /// </summary>
        public static string Weight {
            get {
                return ResourceManager.GetString("Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Wheel color.
        /// </summary>
        public static string WheelColor {
            get {
                return ResourceManager.GetString("WheelColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Width.
        /// </summary>
        public static string Width {
            get {
                return ResourceManager.GetString("Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Winter.
        /// </summary>
        public static string Winter {
            get {
                return ResourceManager.GetString("Winter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на With tolerances.
        /// </summary>
        public static string WithTolerances {
            get {
                return ResourceManager.GetString("WithTolerances", resourceCulture);
            }
        }
    }
}
