//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Term.Web.Views.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Help {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Help() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Term.Web.Views.Resources.Help", typeof(Help).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на All photos.
        /// </summary>
        public static string AllPhotos {
            get {
                return ResourceManager.GetString("AllPhotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на BLACK.
        /// </summary>
        public static string BK {
            get {
                return ResourceManager.GetString("BK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на BLACK+BLUE.
        /// </summary>
        public static string BKBL {
            get {
                return ResourceManager.GetString("BKBL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на BLACK WITH BLUE STRIP INSIDE.
        /// </summary>
        public static string BKBSI {
            get {
                return ResourceManager.GetString("BKBSI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на BLACK FULLY POLISHED WITH BLUE STRIP INSIDE.
        /// </summary>
        public static string BKFBSI {
            get {
                return ResourceManager.GetString("BKFBSI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на BLACK FULLY POLISHED.
        /// </summary>
        public static string BKFFBKFBKFP {
            get {
                return ResourceManager.GetString("BKFFBKFBKFP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на BLACK POLISHED STRIP.
        /// </summary>
        public static string BKFL {
            get {
                return ResourceManager.GetString("BKFL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на BLACK FULLY POLISHED WITH POLISHED LIP.
        /// </summary>
        public static string BKFPL {
            get {
                return ResourceManager.GetString("BKFPL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на BLACK FULLY POLISHED WITH PLASTIC INSERTS.
        /// </summary>
        public static string BKFplastic {
            get {
                return ResourceManager.GetString("BKFplastic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на BLACK FULLY POLISHED WITH POLISHED STRIP INSIDE.
        /// </summary>
        public static string BKFPSIBKFRSI {
            get {
                return ResourceManager.GetString("BKFPSIBKFRSI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на BLACK FULLY POLISHED+POLISHED UNDERCUT.
        /// </summary>
        public static string BKFPU {
            get {
                return ResourceManager.GetString("BKFPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на BLACK FULLY POLISHED+RED.
        /// </summary>
        public static string BKFR {
            get {
                return ResourceManager.GetString("BKFR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на BLACK FULLY POLISHED WITH RED STRIP.
        /// </summary>
        public static string BKFRS {
            get {
                return ResourceManager.GetString("BKFRS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на BLACK FULLY POLISHED RED STRIP INSIDE.
        /// </summary>
        public static string BKFRSI {
            get {
                return ResourceManager.GetString("BKFRSI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на BLACK FULLY POLISHED WITH WHITE STRIP INSIDE.
        /// </summary>
        public static string BKFWSI {
            get {
                return ResourceManager.GetString("BKFWSI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на BLACK FULLY POLISHED WITH YELLOW STRIP INSIDE.
        /// </summary>
        public static string BKFYSI {
            get {
                return ResourceManager.GetString("BKFYSI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на BLACK WITH POLISHED LIP.
        /// </summary>
        public static string BKPL {
            get {
                return ResourceManager.GetString("BKPL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на BLACK+plastic inserts.
        /// </summary>
        public static string BKplastic {
            get {
                return ResourceManager.GetString("BKplastic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на BLACK POLISHED WITH RED STRIP.
        /// </summary>
        public static string BKPRS {
            get {
                return ResourceManager.GetString("BKPRS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на BLACK POLISHED STRIP.
        /// </summary>
        public static string BKPS {
            get {
                return ResourceManager.GetString("BKPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на BLACK+RED.
        /// </summary>
        public static string BKR {
            get {
                return ResourceManager.GetString("BKR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на BLACK WITH RED STRIP.
        /// </summary>
        public static string BKRS {
            get {
                return ResourceManager.GetString("BKRS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на BLACK WITH RED STRIP INSIDE.
        /// </summary>
        public static string BKRSI {
            get {
                return ResourceManager.GetString("BKRSI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на BLACK WITH WHITE STRIP.
        /// </summary>
        public static string BKWS {
            get {
                return ResourceManager.GetString("BKWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на BLACK WITH YELLOW STRIP.
        /// </summary>
        public static string BKY {
            get {
                return ResourceManager.GetString("BKY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на BLACK WITH YELLOW STRIP INSIDE.
        /// </summary>
        public static string BKYS {
            get {
                return ResourceManager.GetString("BKYS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на BLACK.
        /// </summary>
        public static string BLACK {
            get {
                return ResourceManager.GetString("BLACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на BLUE POLISHED.
        /// </summary>
        public static string BLF {
            get {
                return ResourceManager.GetString("BLF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на BLACK+RED.
        /// </summary>
        public static string BR {
            get {
                return ResourceManager.GetString("BR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на BLACK+WHITE.
        /// </summary>
        public static string BW {
            get {
                return ResourceManager.GetString("BW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на BLACK+WHITE+RED STRIP.
        /// </summary>
        public static string BWRS {
            get {
                return ResourceManager.GetString("BWRS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на BLACK+WHITE+WHITE STRIP INSIDE.
        /// </summary>
        public static string BWWSI {
            get {
                return ResourceManager.GetString("BWWSI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на CHROME.
        /// </summary>
        public static string CHROME {
            get {
                return ResourceManager.GetString("CHROME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Color definition.
        /// </summary>
        public static string ColorDefinition {
            get {
                return ResourceManager.GetString("ColorDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на DARK BLUE POLISHED.
        /// </summary>
        public static string DBF {
            get {
                return ResourceManager.GetString("DBF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Feedback.
        /// </summary>
        public static string Feedback0 {
            get {
                return ResourceManager.GetString("Feedback0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Leave feedback.
        /// </summary>
        public static string Feedback1 {
            get {
                return ResourceManager.GetString("Feedback1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Move to.
        /// </summary>
        public static string Feedback10 {
            get {
                return ResourceManager.GetString("Feedback10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на main page.
        /// </summary>
        public static string Feedback11 {
            get {
                return ResourceManager.GetString("Feedback11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на to continue.
        /// </summary>
        public static string Feedback12 {
            get {
                return ResourceManager.GetString("Feedback12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Your opinion and evaluation of Terminal program work is really important for us. You are welcomed to ask questions and send you suggestion for improvement any time. Your message will be automatically directed to Client’s service and our manager will contact you if required..
        /// </summary>
        public static string Feedback2 {
            get {
                return ResourceManager.GetString("Feedback2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name.
        /// </summary>
        public static string Feedback3 {
            get {
                return ResourceManager.GetString("Feedback3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Email.
        /// </summary>
        public static string Feedback4 {
            get {
                return ResourceManager.GetString("Feedback4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Phone.
        /// </summary>
        public static string Feedback5 {
            get {
                return ResourceManager.GetString("Feedback5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Message text.
        /// </summary>
        public static string Feedback6 {
            get {
                return ResourceManager.GetString("Feedback6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Send.
        /// </summary>
        public static string Feedback7 {
            get {
                return ResourceManager.GetString("Feedback7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Thank you for you message!.
        /// </summary>
        public static string Feedback8 {
            get {
                return ResourceManager.GetString("Feedback8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sending failed.
        /// </summary>
        public static string Feedback9 {
            get {
                return ResourceManager.GetString("Feedback9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на GUN METAL.
        /// </summary>
        public static string GM {
            get {
                return ResourceManager.GetString("GM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на GUN METAL+BLACK.
        /// </summary>
        public static string GMB {
            get {
                return ResourceManager.GetString("GMB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на GUN METAL WITH BLUE STRIP INSIDE.
        /// </summary>
        public static string GMBSI {
            get {
                return ResourceManager.GetString("GMBSI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на GUN METAL WITH CROME PLATE.
        /// </summary>
        public static string GMCH {
            get {
                return ResourceManager.GetString("GMCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на GUN METAL FULLY POLISHED.
        /// </summary>
        public static string GMFFGMFGMFP {
            get {
                return ResourceManager.GetString("GMFFGMFGMFP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на GUN METAL FULLY POLISHED WITH PLASTIC INSERTS.
        /// </summary>
        public static string GMFplastic {
            get {
                return ResourceManager.GetString("GMFplastic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на GUN METAL POLISHED LIP.
        /// </summary>
        public static string GMPL {
            get {
                return ResourceManager.GetString("GMPL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на GUN METAL+plastic.
        /// </summary>
        public static string GMplastic {
            get {
                return ResourceManager.GetString("GMplastic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на GUN METAL POLISHED STRIP.
        /// </summary>
        public static string GMPS {
            get {
                return ResourceManager.GetString("GMPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на GUN METAL WITH RED STRIP.
        /// </summary>
        public static string GMRS {
            get {
                return ResourceManager.GetString("GMRS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на GUN METAL WITH RED STRIP INSIDE.
        /// </summary>
        public static string GMRSI {
            get {
                return ResourceManager.GetString("GMRSI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на GUN METAL WHITE STRIP INSIDE.
        /// </summary>
        public static string GMWSI {
            get {
                return ResourceManager.GetString("GMWSI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на HYPER SILVER.
        /// </summary>
        public static string HS {
            get {
                return ResourceManager.GetString("HS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MATT BLACK.
        /// </summary>
        public static string MB {
            get {
                return ResourceManager.GetString("MB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MATT BLACK +BLUE.
        /// </summary>
        public static string MBBL {
            get {
                return ResourceManager.GetString("MBBL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MATT BLACK POLISHED.
        /// </summary>
        public static string MBFMBFLMBFP {
            get {
                return ResourceManager.GetString("MBFMBFLMBFP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MATT BLACK POLISHED +RED.
        /// </summary>
        public static string MBFR {
            get {
                return ResourceManager.GetString("MBFR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MATT BLACK FULLY POLISHED WITH RED STRIP.
        /// </summary>
        public static string MBFRS {
            get {
                return ResourceManager.GetString("MBFRS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MATT BLACK FULLY POLISHED WITH RED STRIP INSIDE.
        /// </summary>
        public static string MBFRSI {
            get {
                return ResourceManager.GetString("MBFRSI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MATT BLACK MATT POLISHED.
        /// </summary>
        public static string MBMF {
            get {
                return ResourceManager.GetString("MBMF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MATT BLACK WITH ORANGE AND GREY STRIPS.
        /// </summary>
        public static string MBOGS {
            get {
                return ResourceManager.GetString("MBOGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MATT BLACK POLISHED LIP.
        /// </summary>
        public static string MBPL {
            get {
                return ResourceManager.GetString("MBPL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MATT BLACK POLISHED STRIP.
        /// </summary>
        public static string MBPS {
            get {
                return ResourceManager.GetString("MBPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MATT BLACK + RED.
        /// </summary>
        public static string MBR {
            get {
                return ResourceManager.GetString("MBR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MATT BLACK +RED+MILLING.
        /// </summary>
        public static string MBRM {
            get {
                return ResourceManager.GetString("MBRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MATT BROWN+RED MILLING.
        /// </summary>
        public static string MBRRM {
            get {
                return ResourceManager.GetString("MBRRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MATT BLACK WITH RED STRIP.
        /// </summary>
        public static string MBRS {
            get {
                return ResourceManager.GetString("MBRS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MATT BLACK WITH RED STRIP INSIDE.
        /// </summary>
        public static string MBRSI {
            get {
                return ResourceManager.GetString("MBRSI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MATT BLACK WITH STAINLESS STEEL LIP.
        /// </summary>
        public static string MBSSL {
            get {
                return ResourceManager.GetString("MBSSL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MATT BLACK +WHITE INSERTS.
        /// </summary>
        public static string MBWHITEINSERT {
            get {
                return ResourceManager.GetString("MBWHITEINSERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MATT BLACK WHITE STRIP INSIDE.
        /// </summary>
        public static string MBWSI {
            get {
                return ResourceManager.GetString("MBWSI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MATT BLACK+YELLOW.
        /// </summary>
        public static string MBY {
            get {
                return ResourceManager.GetString("MBY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MATT BLACK WITH YELLOW STRIP.
        /// </summary>
        public static string MBYS {
            get {
                return ResourceManager.GetString("MBYS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MATT BLACK WITH YELLOW STRIP INSIDE+YELLOW.
        /// </summary>
        public static string MBYSIY {
            get {
                return ResourceManager.GetString("MBYSIY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MATT GUN METAL.
        /// </summary>
        public static string MGM {
            get {
                return ResourceManager.GetString("MGM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MATT GUN METAL WITH BLUE STRIP INSIDE.
        /// </summary>
        public static string MGMBSI {
            get {
                return ResourceManager.GetString("MGMBSI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MATT GUN METAL POLISHED.
        /// </summary>
        public static string MGMF {
            get {
                return ResourceManager.GetString("MGMF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MATT GUN METAL+ YELLOW.
        /// </summary>
        public static string MGMY {
            get {
                return ResourceManager.GetString("MGMY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MATT WHITE.
        /// </summary>
        public static string MW {
            get {
                return ResourceManager.GetString("MW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MATT WHITE WITH POLISHED LIP.
        /// </summary>
        public static string MWPL {
            get {
                return ResourceManager.GetString("MWPL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MATT WHITE RED STRIP INSIDE.
        /// </summary>
        public static string MWRSI {
            get {
                return ResourceManager.GetString("MWRSI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на RED+BLACK+POLISHED.
        /// </summary>
        public static string RBF {
            get {
                return ResourceManager.GetString("RBF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SILVER.
        /// </summary>
        public static string S {
            get {
                return ResourceManager.GetString("S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SILVER+BLACK.
        /// </summary>
        public static string SB {
            get {
                return ResourceManager.GetString("SB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SILVER WITH CROME PLATE.
        /// </summary>
        public static string SCH {
            get {
                return ResourceManager.GetString("SCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SILVER POLISHED+BLACK.
        /// </summary>
        public static string SFB {
            get {
                return ResourceManager.GetString("SFB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SILVER FULLY POLISHED.
        /// </summary>
        public static string SFFSFSFP {
            get {
                return ResourceManager.GetString("SFFSFSFP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SILVER.
        /// </summary>
        public static string SILVER {
            get {
                return ResourceManager.GetString("SILVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SILVER WITH POLISHED LIP.
        /// </summary>
        public static string SPL {
            get {
                return ResourceManager.GetString("SPL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SILVER+plastic.
        /// </summary>
        public static string Splastic {
            get {
                return ResourceManager.GetString("Splastic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SILVER+PLASTIC+RED STRIP.
        /// </summary>
        public static string SPLASTICRS {
            get {
                return ResourceManager.GetString("SPLASTICRS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SILVER WITH RED STRIP.
        /// </summary>
        public static string SRS {
            get {
                return ResourceManager.GetString("SRS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Instruction for project.
        /// </summary>
        public static string TextHelp1 {
            get {
                return ResourceManager.GetString("TextHelp1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Download available stock in Excel format.
        /// </summary>
        public static string TextHelp10 {
            get {
                return ResourceManager.GetString("TextHelp10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string TextHelp11 {
            get {
                return ResourceManager.GetString("TextHelp11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Wholesale pricing.
        /// </summary>
        public static string TextHelp12 {
            get {
                return ResourceManager.GetString("TextHelp12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Retail pricing.
        /// </summary>
        public static string TextHelp13 {
            get {
                return ResourceManager.GetString("TextHelp13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Blocking or deleting of Points.
        /// </summary>
        public static string TextHelp14 {
            get {
                return ResourceManager.GetString("TextHelp14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Product search: code, size, vehicle.
        /// </summary>
        public static string TextHelp15 {
            get {
                return ResourceManager.GetString("TextHelp15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The search can be performed in 3 ways:.
        /// </summary>
        public static string TextHelp16 {
            get {
                return ResourceManager.GetString("TextHelp16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Any product name in the upper menu window.
        /// </summary>
        public static string TextHelp17 {
            get {
                return ResourceManager.GetString("TextHelp17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Parameters search.
        /// </summary>
        public static string TextHelp18 {
            get {
                return ResourceManager.GetString("TextHelp18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Vehicle search.
        /// </summary>
        public static string TextHelp19 {
            get {
                return ResourceManager.GetString("TextHelp19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Terminal.
        /// </summary>
        public static string TextHelp2 {
            get {
                return ResourceManager.GetString("TextHelp2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Product reservation.
        /// </summary>
        public static string TextHelp20 {
            get {
                return ResourceManager.GetString("TextHelp20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на After you find the required product, you need to indicate required amount and press “add to cart”, the product will be added to cart. You can add as many products as you need. Maximum order of 1 position is restricted to 200pc. Products added to Cart are underlined green. After order is formed it is required to check availability and confirm it. Go to cart and press “check order correctness” in the right upper corner window..
        /// </summary>
        public static string TextHelp21 {
            get {
                return ResourceManager.GetString("TextHelp21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You can add comments to the Order, such as contact person and contact number for sms-notification. .
        /// </summary>
        public static string TextHelp22 {
            get {
                return ResourceManager.GetString("TextHelp22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reservation lasts 7 days..
        /// </summary>
        public static string TextHelp23 {
            get {
                return ResourceManager.GetString("TextHelp23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Creation of Points.
        /// </summary>
        public static string TextHelp24 {
            get {
                return ResourceManager.GetString("TextHelp24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на In order to add new Point, go to Menu:.
        /// </summary>
        public static string TextHelp25 {
            get {
                return ResourceManager.GetString("TextHelp25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Press “Add Point” in upper left corner..
        /// </summary>
        public static string TextHelp26 {
            get {
                return ResourceManager.GetString("TextHelp26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Read below how to set.
        /// </summary>
        public static string TextHelp27 {
            get {
                return ResourceManager.GetString("TextHelp27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на pricing for the Points.
        /// </summary>
        public static string TextHelp28 {
            get {
                return ResourceManager.GetString("TextHelp28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Order change or cancelling.
        /// </summary>
        public static string TextHelp29 {
            get {
                return ResourceManager.GetString("TextHelp29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сontent.
        /// </summary>
        public static string TextHelp3 {
            get {
                return ResourceManager.GetString("TextHelp3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на In order to change, cancel, see your orders, go to Menu:.
        /// </summary>
        public static string TextHelp30 {
            get {
                return ResourceManager.GetString("TextHelp30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Here you can see the history.
        /// </summary>
        public static string TextHelp31 {
            get {
                return ResourceManager.GetString("TextHelp31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на of your orders, their status, date of shipment, comment, Point where the order came from, print out invoice. You can see entry price and the price you sold the product..
        /// </summary>
        public static string TextHelp32 {
            get {
                return ResourceManager.GetString("TextHelp32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sales and order follow up..
        /// </summary>
        public static string TextHelp33 {
            get {
                return ResourceManager.GetString("TextHelp33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на In order to see product sales, go Menu:.
        /// </summary>
        public static string TextHelp34 {
            get {
                return ResourceManager.GetString("TextHelp34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Here you can see history of sales, date of shipment, contacts of driver, comments, and print out the invoice..
        /// </summary>
        public static string TextHelp35 {
            get {
                return ResourceManager.GetString("TextHelp35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Password to enter settings.
        /// </summary>
        public static string TextHelp36 {
            get {
                return ResourceManager.GetString("TextHelp36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Password is required, that no one can enter this Menu and change settings.
        /// </summary>
        public static string TextHelp37 {
            get {
                return ResourceManager.GetString("TextHelp37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Password is established and changed in the Settings of your Terminal Point..
        /// </summary>
        public static string TextHelp38 {
            get {
                return ResourceManager.GetString("TextHelp38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Download Excel file with available stock.
        /// </summary>
        public static string TextHelp39 {
            get {
                return ResourceManager.GetString("TextHelp39", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Product search: code, size, vehicle.
        /// </summary>
        public static string TextHelp4 {
            get {
                return ResourceManager.GetString("TextHelp4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You can download Excel file with available stock in the Menu:.
        /// </summary>
        public static string TextHelp40 {
            get {
                return ResourceManager.GetString("TextHelp40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The file will be formed with your entry and retail price..
        /// </summary>
        public static string TextHelp41 {
            get {
                return ResourceManager.GetString("TextHelp41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string TextHelp42 {
            get {
                return ResourceManager.GetString("TextHelp42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string TextHelp43 {
            get {
                return ResourceManager.GetString("TextHelp43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string TextHelp44 {
            get {
                return ResourceManager.GetString("TextHelp44", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Wholesale price forming.
        /// </summary>
        public static string TextHelp45 {
            get {
                return ResourceManager.GetString("TextHelp45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You need to establish price for each Point. It is established in the settings of each Point..
        /// </summary>
        public static string TextHelp46 {
            get {
                return ResourceManager.GetString("TextHelp46", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Price can be set in relation to basic price, with the extra charge to your entry price, or as manufacturer recommended price. This price will be shown as an entry price for your Point.  If you do not want to show price to the client, mark window “hide price”. If you do not want to show the producer, mark window “hide producer”. Pricing can be established for each producer separately, and also for group of product (wheels, tires)..
        /// </summary>
        public static string TextHelp47 {
            get {
                return ResourceManager.GetString("TextHelp47", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Price for batteries and accessories is formed as following:.
        /// </summary>
        public static string TextHelp48 {
            get {
                return ResourceManager.GetString("TextHelp48", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Extra charge for all batteries for Point is 10%.
        /// </summary>
        public static string TextHelp49 {
            get {
                return ResourceManager.GetString("TextHelp49", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reservation of product.
        /// </summary>
        public static string TextHelp5 {
            get {
                return ResourceManager.GetString("TextHelp5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Extra charge for accessories for Point is 20%.
        /// </summary>
        public static string TextHelp50 {
            get {
                return ResourceManager.GetString("TextHelp50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Retail price forming.
        /// </summary>
        public static string TextHelp51 {
            get {
                return ResourceManager.GetString("TextHelp51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You have to establish retail price in the Settings..
        /// </summary>
        public static string TextHelp52 {
            get {
                return ResourceManager.GetString("TextHelp52", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Price can be set in relation to basic price, with the extra charge to your entry price, or as manufacturer recommended price. This price will be shown as sale price. If you do not want to show price to the client, mark window “hide price”. If you do not want to show the producer, mark window “hide producer”.  Pricing can be established for each producer separately, and also for group of product (wheels, tires). If you want to see your entry price, you have to establish 0% extra charge for all product groups [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string TextHelp53 {
            get {
                return ResourceManager.GetString("TextHelp53", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Price for batteries and accessories is formed as following:.
        /// </summary>
        public static string TextHelp54 {
            get {
                return ResourceManager.GetString("TextHelp54", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на End customer price for batteries +40%.
        /// </summary>
        public static string TextHelp55 {
            get {
                return ResourceManager.GetString("TextHelp55", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на End customer price for accessories +50%.
        /// </summary>
        public static string TextHelp56 {
            get {
                return ResourceManager.GetString("TextHelp56", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Blocking and deleting of Points.
        /// </summary>
        public static string TextHelp57 {
            get {
                return ResourceManager.GetString("TextHelp57", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You can block or delete your Points in Menu:.
        /// </summary>
        public static string TextHelp58 {
            get {
                return ResourceManager.GetString("TextHelp58", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на % from purchase (from the purchase price, established for the Terminal client).
        /// </summary>
        public static string TextHelp59 {
            get {
                return ResourceManager.GetString("TextHelp59", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Addition of Points.
        /// </summary>
        public static string TextHelp6 {
            get {
                return ResourceManager.GetString("TextHelp6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Clear the price (zero price is shown or no price).
        /// </summary>
        public static string TextHelp60 {
            get {
                return ResourceManager.GetString("TextHelp60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Clear the brand  (the brand is not shown).
        /// </summary>
        public static string TextHelp61 {
            get {
                return ResourceManager.GetString("TextHelp61", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Price for car batteries and accessories is established as following:.
        /// </summary>
        public static string TextHelp62 {
            get {
                return ResourceManager.GetString("TextHelp62", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на For all car batteries extra charge for end client is 40%.
        /// </summary>
        public static string TextHelp63 {
            get {
                return ResourceManager.GetString("TextHelp63", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на For all accessories extra charge for end client is 50%.
        /// </summary>
        public static string TextHelp64 {
            get {
                return ResourceManager.GetString("TextHelp64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на After all settings are saved, the Point is to read and agree with license agreement and check the box “I accept the Agreement conditions”..
        /// </summary>
        public static string TextHelp65 {
            get {
                return ResourceManager.GetString("TextHelp65", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The Point can control orders created under its account data. It can edit its orders and orders of Points within 7 days from order date..
        /// </summary>
        public static string TextHelp66 {
            get {
                return ResourceManager.GetString("TextHelp66", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The point controls its purchase and sale price via Menu Settings..
        /// </summary>
        public static string TextHelp67 {
            get {
                return ResourceManager.GetString("TextHelp67", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Order changing and cancelling.
        /// </summary>
        public static string TextHelp7 {
            get {
                return ResourceManager.GetString("TextHelp7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Order follow up.
        /// </summary>
        public static string TextHelp8 {
            get {
                return ResourceManager.GetString("TextHelp8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Password for settings adjustment.
        /// </summary>
        public static string TextHelp9 {
            get {
                return ResourceManager.GetString("TextHelp9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Assistance.
        /// </summary>
        public static string TitleHelp {
            get {
                return ResourceManager.GetString("TitleHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Upload wheel photos.
        /// </summary>
        public static string UploadWheelPhotos {
            get {
                return ResourceManager.GetString("UploadWheelPhotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на WHITE.
        /// </summary>
        public static string W {
            get {
                return ResourceManager.GetString("W", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на WHITE +BLACK.
        /// </summary>
        public static string WB {
            get {
                return ResourceManager.GetString("WB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на WHITE +BLACK+BLACK STRIP INSIDE.
        /// </summary>
        public static string WBBSI {
            get {
                return ResourceManager.GetString("WBBSI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на WHITE +BLUE.
        /// </summary>
        public static string WBL {
            get {
                return ResourceManager.GetString("WBL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на WHITE+BLACK INSERT.
        /// </summary>
        public static string WBLACKINSERT {
            get {
                return ResourceManager.GetString("WBLACKINSERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на WHITE +BLACK+RED STRIP.
        /// </summary>
        public static string WBRS {
            get {
                return ResourceManager.GetString("WBRS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на WHITE +BLACK+RED STRIP+BLACK STRIP INSIDE.
        /// </summary>
        public static string WBRSBSI {
            get {
                return ResourceManager.GetString("WBRSBSI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на WHITE BLACK STRIP.
        /// </summary>
        public static string WBS {
            get {
                return ResourceManager.GetString("WBS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на WHITE BLACK STRIP INSIDE.
        /// </summary>
        public static string WBSI {
            get {
                return ResourceManager.GetString("WBSI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на WHITE+BLACK+WHITE STRIP.
        /// </summary>
        public static string WBWS {
            get {
                return ResourceManager.GetString("WBWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на WHITE FULLY POLISHED.
        /// </summary>
        public static string WF {
            get {
                return ResourceManager.GetString("WF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на WHITE FULLY POLISHED WITH POLISHED LIP.
        /// </summary>
        public static string WFPL {
            get {
                return ResourceManager.GetString("WFPL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на WHITE FULLY POLISHED WITH RED STRIP INSIDE.
        /// </summary>
        public static string WFRSI {
            get {
                return ResourceManager.GetString("WFRSI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Wheel photos.
        /// </summary>
        public static string WheelPhotos {
            get {
                return ResourceManager.GetString("WheelPhotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на WHITE.
        /// </summary>
        public static string WHITE {
            get {
                return ResourceManager.GetString("WHITE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на WHITE +RED.
        /// </summary>
        public static string WR {
            get {
                return ResourceManager.GetString("WR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на WHITE RED STRIP.
        /// </summary>
        public static string WREDS {
            get {
                return ResourceManager.GetString("WREDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на WHITE AND RED MILLING.
        /// </summary>
        public static string WRS {
            get {
                return ResourceManager.GetString("WRS", resourceCulture);
            }
        }
    }
}
