//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Term.Web.Views.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SeasonOrdersTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SeasonOrdersTexts() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Term.Web.Views.Resources.SeasonOrdersTexts", typeof(SeasonOrdersTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Analize.
        /// </summary>
        public static string Analyse {
            get {
                return ResourceManager.GetString("Analyse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Analysis of order.
        /// </summary>
        public static string AnalysisOfOrder {
            get {
                return ResourceManager.GetString("AnalysisOfOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Begin date.
        /// </summary>
        public static string BeginDate {
            get {
                return ResourceManager.GetString("BeginDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Code.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Date of validity must be between.
        /// </summary>
        public static string DateValidity {
            get {
                return ResourceManager.GetString("DateValidity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на End date.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Amount of products in added to cart should be between 1 and 1000.
        /// </summary>
        public static string Error_AmountOfCountShouldBeBetween0And1000 {
            get {
                return ResourceManager.GetString("Error_AmountOfCountShouldBeBetween0And1000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No factory given for this product.
        /// </summary>
        public static string Error_NoFactoryForProduct {
            get {
                return ResourceManager.GetString("Error_NoFactoryForProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No product found by this code.
        /// </summary>
        public static string Error_NoProductFoundByCode {
            get {
                return ResourceManager.GetString("Error_NoProductFoundByCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No season items found for this product.
        /// </summary>
        public static string Error_NoSeasonItemsFoundForThisProduct {
            get {
                return ResourceManager.GetString("Error_NoSeasonItemsFoundForThisProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на From.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Indicate date of order validity (up to).
        /// </summary>
        public static string IndicateDate {
            get {
                return ResourceManager.GetString("IndicateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на In reserve.
        /// </summary>
        public static string InReserve {
            get {
                return ResourceManager.GetString("InReserve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Your order from production.
        /// </summary>
        public static string MsgCreate1 {
            get {
                return ResourceManager.GetString("MsgCreate1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string MsgCreate2 {
            get {
                return ResourceManager.GetString("MsgCreate2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на successfully created..
        /// </summary>
        public static string MsgCreate3 {
            get {
                return ResourceManager.GetString("MsgCreate3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на On way available.
        /// </summary>
        public static string OnWayAvailable {
            get {
                return ResourceManager.GetString("OnWayAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The order is successfully changed.
        /// </summary>
        public static string OrderChanged {
            get {
                return ResourceManager.GetString("OrderChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Print.
        /// </summary>
        public static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name.
        /// </summary>
        public static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Quantity.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Quantity on way.
        /// </summary>
        public static string QuantityOnWay {
            get {
                return ResourceManager.GetString("QuantityOnWay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rest.
        /// </summary>
        public static string RestToShip {
            get {
                return ResourceManager.GetString("RestToShip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на search by order number.
        /// </summary>
        public static string SearchByOrderNamber {
            get {
                return ResourceManager.GetString("SearchByOrderNamber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Orders from production.
        /// </summary>
        public static string SeasonOrders {
            get {
                return ResourceManager.GetString("SeasonOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Shipped.
        /// </summary>
        public static string Shipped {
            get {
                return ResourceManager.GetString("Shipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на By status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Under the order 21 days.
        /// </summary>
        public static string ToOrder60Days {
            get {
                return ResourceManager.GetString("ToOrder60Days", resourceCulture);
            }
        }
    }
}
