//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Term.Web.Views.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Settings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Settings() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Term.Web.Views.Resources.Settings", typeof(Settings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Actions.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Additional stock.
        /// </summary>
        public static string AdditionalStock {
            get {
                return ResourceManager.GetString("AdditionalStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add Point.
        /// </summary>
        public static string AddPoint {
            get {
                return ResourceManager.GetString("AddPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The delivery address of the goods to your stock.
        /// </summary>
        public static string AddressForDelivery {
            get {
                return ResourceManager.GetString("AddressForDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Location of the Terminal client .
        /// </summary>
        public static string AddressForEditForm {
            get {
                return ResourceManager.GetString("AddressForEditForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Set marker on map or use the search field.
        /// </summary>
        public static string AddressForEditForm2 {
            get {
                return ResourceManager.GetString("AddressForEditForm2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Apply to all brands.
        /// </summary>
        public static string ApplyAllBrands {
            get {
                return ResourceManager.GetString("ApplyAllBrands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на % off basic.
        /// </summary>
        public static string BasicPrice {
            get {
                return ResourceManager.GetString("BasicPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Block.
        /// </summary>
        public static string Block {
            get {
                return ResourceManager.GetString("Block", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Brand.
        /// </summary>
        public static string Brand {
            get {
                return ResourceManager.GetString("Brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Central stock.
        /// </summary>
        public static string CentralStock {
            get {
                return ResourceManager.GetString("CentralStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Clear.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Clear the brand.
        /// </summary>
        public static string ClearTheBrand {
            get {
                return ResourceManager.GetString("ClearTheBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Clear the price.
        /// </summary>
        public static string ClearThePrice {
            get {
                return ResourceManager.GetString("ClearThePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name of your company.
        /// </summary>
        public static string CompName {
            get {
                return ResourceManager.GetString("CompName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Block?.
        /// </summary>
        public static string ConfBlock {
            get {
                return ResourceManager.GetString("ConfBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sure to block point.
        /// </summary>
        public static string ConfBlockAsk {
            get {
                return ResourceManager.GetString("ConfBlockAsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string ConfBlockText {
            get {
                return ResourceManager.GetString("ConfBlockText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete?.
        /// </summary>
        public static string ConfDel {
            get {
                return ResourceManager.GetString("ConfDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sure to delete point.
        /// </summary>
        public static string ConfDelAsk {
            get {
                return ResourceManager.GetString("ConfDelAsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на If you delete point, all the setting will be lost.
        /// </summary>
        public static string ConfDelText {
            get {
                return ResourceManager.GetString("ConfDelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Yes. Delete.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Contact details.
        /// </summary>
        public static string ContactDetails {
            get {
                return ResourceManager.GetString("ContactDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name of contact person.
        /// </summary>
        public static string ContactPerson {
            get {
                return ResourceManager.GetString("ContactPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Contact person.
        /// </summary>
        public static string ContactPersonEdit {
            get {
                return ResourceManager.GetString("ContactPersonEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create Point.
        /// </summary>
        public static string CreatePoint {
            get {
                return ResourceManager.GetString("CreatePoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Currency.
        /// </summary>
        public static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Time of delivery.
        /// </summary>
        public static string DeliveryFrom {
            get {
                return ResourceManager.GetString("DeliveryFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Time of delivery from additional stock.
        /// </summary>
        public static string DeliveryFromAddStock {
            get {
                return ResourceManager.GetString("DeliveryFromAddStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Time of delivery from central stock.
        /// </summary>
        public static string DeliveryFromCentralStock {
            get {
                return ResourceManager.GetString("DeliveryFromCentralStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit settings.
        /// </summary>
        public static string EditSettings {
            get {
                return ResourceManager.GetString("EditSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на End customer.
        /// </summary>
        public static string EndCustomer {
            get {
                return ResourceManager.GetString("EndCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на number of days must be between 1 and 45.
        /// </summary>
        public static string ErrorDays {
            get {
                return ResourceManager.GetString("ErrorDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fill out the field.
        /// </summary>
        public static string ErrorList {
            get {
                return ResourceManager.GetString("ErrorList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Date of shipment should  be in range from 1 to 45.
        /// </summary>
        public static string ErrorRangeDays {
            get {
                return ResourceManager.GetString("ErrorRangeDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fault! Settings are not saved..
        /// </summary>
        public static string ErrorSettingsSaved {
            get {
                return ResourceManager.GetString("ErrorSettingsSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Not allowed to delete own Point.
        /// </summary>
        public static string ErrorToDelMainPoint {
            get {
                return ResourceManager.GetString("ErrorToDelMainPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This Point has orders. Not possible to delete.
        /// </summary>
        public static string ErrorToDelPointHaveOrder {
            get {
                return ResourceManager.GetString("ErrorToDelPointHaveOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fill in location address.
        /// </summary>
        public static string FillInAddress {
            get {
                return ResourceManager.GetString("FillInAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fill in company&apos;s name.
        /// </summary>
        public static string FillInCompName {
            get {
                return ResourceManager.GetString("FillInCompName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fill in name.
        /// </summary>
        public static string FillInName {
            get {
                return ResourceManager.GetString("FillInName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fill in phone.
        /// </summary>
        public static string FillInPhone {
            get {
                return ResourceManager.GetString("FillInPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на List of points.
        /// </summary>
        public static string ListPoints {
            get {
                return ResourceManager.GetString("ListPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Lock.
        /// </summary>
        public static string Lock {
            get {
                return ResourceManager.GetString("Lock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Company logo or photo.
        /// </summary>
        public static string LogoOrPhoto {
            get {
                return ResourceManager.GetString("LogoOrPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Main stock.
        /// </summary>
        public static string MainStock {
            get {
                return ResourceManager.GetString("MainStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name of Point.
        /// </summary>
        public static string NamePoint {
            get {
                return ResourceManager.GetString("NamePoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Not able to create Point.
        /// </summary>
        public static string NotCreate {
            get {
                return ResourceManager.GetString("NotCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Not selected.
        /// </summary>
        public static string NotSelected {
            get {
                return ResourceManager.GetString("NotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на On-line shop.
        /// </summary>
        public static string OnlineShop {
            get {
                return ResourceManager.GetString("OnlineShop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open settings.
        /// </summary>
        public static string OpenSettings {
            get {
                return ResourceManager.GetString("OpenSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Password to enter settings.
        /// </summary>
        public static string PasswordToSettings {
            get {
                return ResourceManager.GetString("PasswordToSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Phone number.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Point.
        /// </summary>
        public static string Point {
            get {
                return ResourceManager.GetString("Point", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Price settings for end client.
        /// </summary>
        public static string PriceSettings {
            get {
                return ResourceManager.GetString("PriceSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Price settings for accessories for end client.
        /// </summary>
        public static string PriceSettingsAcc {
            get {
                return ResourceManager.GetString("PriceSettingsAcc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Price settings for car batteries for end client.
        /// </summary>
        public static string PriceSettingsBat {
            get {
                return ResourceManager.GetString("PriceSettingsBat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Price settings for tyres for end client.
        /// </summary>
        public static string PriceSettingsTyres {
            get {
                return ResourceManager.GetString("PriceSettingsTyres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Price settings for wheels for end client.
        /// </summary>
        public static string PriceSettingsWheels {
            get {
                return ResourceManager.GetString("PriceSettingsWheels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Wholesale Price settings .
        /// </summary>
        public static string PriceWholesale {
            get {
                return ResourceManager.GetString("PriceWholesale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Wholesale Price settings for accessories.
        /// </summary>
        public static string PriceWholesaleAcc {
            get {
                return ResourceManager.GetString("PriceWholesaleAcc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Wholesale Price settings for car batteries.
        /// </summary>
        public static string PriceWholesaleBat {
            get {
                return ResourceManager.GetString("PriceWholesaleBat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Wholesale Price settings for tyres.
        /// </summary>
        public static string PriceWholesaleTyres {
            get {
                return ResourceManager.GetString("PriceWholesaleTyres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Wholesale Price settings for wheels.
        /// </summary>
        public static string PriceWholesaleWheels {
            get {
                return ResourceManager.GetString("PriceWholesaleWheels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на % off purchase price.
        /// </summary>
        public static string PurchasePrice {
            get {
                return ResourceManager.GetString("PurchasePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Recommended.
        /// </summary>
        public static string Recommended {
            get {
                return ResourceManager.GetString("Recommended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Responsible manager.
        /// </summary>
        public static string ResponsibleManager {
            get {
                return ResourceManager.GetString("ResponsibleManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Restore.
        /// </summary>
        public static string Restore {
            get {
                return ResourceManager.GetString("Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Retail.
        /// </summary>
        public static string Retail {
            get {
                return ResourceManager.GetString("Retail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sales market.
        /// </summary>
        public static string SalesMarket {
            get {
                return ResourceManager.GetString("SalesMarket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings of .
        /// </summary>
        public static string SettingsChildClient {
            get {
                return ResourceManager.GetString("SettingsChildClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings succesfully saved.
        /// </summary>
        public static string SettingsSaved {
            get {
                return ResourceManager.GetString("SettingsSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings of Terminal clent.
        /// </summary>
        public static string SettingsTermClient {
            get {
                return ResourceManager.GetString("SettingsTermClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Stock.
        /// </summary>
        public static string Stock {
            get {
                return ResourceManager.GetString("Stock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Terminal client.
        /// </summary>
        public static string TerminalClient {
            get {
                return ResourceManager.GetString("TerminalClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Time of delivery from Additional stock.
        /// </summary>
        public static string TimeDeliveryAddStock {
            get {
                return ResourceManager.GetString("TimeDeliveryAddStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Time of delivery from Central stock (Yaroslavl).
        /// </summary>
        public static string TimeDeliveryCentrStock {
            get {
                return ResourceManager.GetString("TimeDeliveryCentrStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Positive number - extra charge, negative - discound from basic price.
        /// </summary>
        public static string TooltipBasic {
            get {
                return ResourceManager.GetString("TooltipBasic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Brand.
        /// </summary>
        public static string TooltipBrand {
            get {
                return ResourceManager.GetString("TooltipBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This photo will be shown in your company profile in sales networks on the following web-pages:NZ, Alcasta, LegeArtis, Yokatta, YST, X-Race,CrossStreet, Trebl, Contyre, Avatyre..
        /// </summary>
        public static string TooltipPhoto {
            get {
                return ResourceManager.GetString("TooltipPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на These data will be shown in your company profile in sales networks on the following web-pages: NZ, Alcasta, LegeArtis, Yokatta, YST, X-Race,CrossStreet, Trebl, Contyre, Avatyre. Your address will be linked to geolocation system for fast search of your shop..
        /// </summary>
        public static string TooltipSalesMarket {
            get {
                return ResourceManager.GetString("TooltipSalesMarket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Extra charge from purchase price.
        /// </summary>
        public static string TooltipZakup {
            get {
                return ResourceManager.GetString("TooltipZakup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unblock.
        /// </summary>
        public static string Unblock {
            get {
                return ResourceManager.GetString("Unblock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на User name.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на User password.
        /// </summary>
        public static string UserPassword {
            get {
                return ResourceManager.GetString("UserPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Web site.
        /// </summary>
        public static string WebSite {
            get {
                return ResourceManager.GetString("WebSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Wholesale.
        /// </summary>
        public static string Wholesale {
            get {
                return ResourceManager.GetString("Wholesale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Your point.
        /// </summary>
        public static string YourPoint {
            get {
                return ResourceManager.GetString("YourPoint", resourceCulture);
            }
        }
    }
}
